# Generated by Django 5.1.1 on 2024-10-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_participant_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='print_title',
            field=models.TextField(default=models.CharField(max_length=100, verbose_name='Категория участника'), verbose_name='Название для печати'),
        ),
    ]
