# Generated by Django 5.1.1 on 2024-10-09 05:02

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_category_category_title_category_print_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='print_title',
            field=models.TextField(default=django.db.models.fields.Field.get_attname, verbose_name='Название для печати'),
        ),
    ]
