# Generated by Django 5.1.1 on 2024-10-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_print_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='print_title',
            field=models.TextField(default=None, verbose_name='Название для печати'),
        ),
    ]
