# Generated by Django 5.1.1 on 2024-10-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_category_print_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Компетенция (номинация)')),
                ('print_title', models.TextField(verbose_name='Название для печати')),
            ],
            options={
                'verbose_name': 'Компетенция (номинация)',
                'verbose_name_plural': 'Компетенции (номинации)',
            },
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.event'),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='first', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='last', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='participant',
            name='middle_name',
            field=models.CharField(default='middle', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='participant',
            name='organization',
            field=models.CharField(default='organisation', max_length=100, verbose_name='Организация'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
