# Generated by Django 5.1.1 on 2024-10-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_author_competency_author_event_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='competency',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='author',
        ),
    ]
