# Generated by Django 5.1.1 on 2024-10-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_category_author_alter_competency_author_and_more'),
        ('home', '0012_remove_category_author_remove_competency_author_and_more'),
    ]

    operations = [
    ]
