# Generated by Django 5.1.1 on 2024-10-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20241028_1730'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.category'),
        ),
        migrations.AddField(
            model_name='participant',
            name='competency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.competency'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.event'),
        ),
    ]
