# Generated by Django 5.1.1 on 2024-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_participant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='competency',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='participant',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='Author'),
        ),
    ]
