# Generated by Django 5.1.1 on 2024-10-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_category_author_competency_author_event_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='home.category'),
        ),
    ]
