# Generated by Django 5.1.1 on 2024-10-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_participant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='competency',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='author',
        ),
    ]
