# Generated by Django 5.1.1 on 2024-10-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_category_author_remove_competency_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='competency',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='author',
        ),
    ]
