# Generated by Django 5.1.1 on 2024-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_category_author_remove_competency_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
