# Generated by Django 5.1.1 on 2024-11-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.event'),
        ),
    ]
