# Generated by Django 5.1.1 on 2024-11-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_profile_created_by_profile_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
