# Generated by Django 5.1.1 on 2024-11-11 08:59

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_profile_current_event_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(null=True, upload_to=home.models.user_directory_path),
        ),
    ]
