# Generated by Django 5.1.1 on 2024-11-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_userimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
