# Generated by Django 5.1.1 on 2024-11-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_userimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_cover', to='home.userimage'),
        ),
    ]
