# Generated by Django 5.1.1 on 2024-12-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover',
        ),
    ]
