# Generated by Django 5.1.1 on 2024-12-16 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_event_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('print_item', models.CharField(choices=[('event', 'Мероприятие'), ('category', 'Категория'), ('competency', 'Компетенция (номинация)'), ('fio', 'Фамилия Имя Отчество'), ('text', 'Текст участника'), ('custom_text', 'Произвольный техт')], max_length=25)),
                ('start_x', models.PositiveSmallIntegerField()),
                ('start_y', models.PositiveSmallIntegerField()),
                ('delta_x', models.PositiveSmallIntegerField()),
                ('delta_y', models.PositiveSmallIntegerField()),
                ('font_size', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон печати',
                'verbose_name_plural': 'Шаблоны печати',
            },
        ),
    ]
