# Generated by Django 5.1.1 on 2024-12-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_printtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='event_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_event_related', to='home.event'),
        ),
    ]
