# Generated by Django 5.1.1 on 2024-12-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='height',
            field=models.PositiveSmallIntegerField(default=297, verbose_name='Высота, мм'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='width',
            field=models.PositiveSmallIntegerField(default=210, verbose_name='Ширина, мм'),
        ),
    ]
