# Generated by Django 5.1.1 on 2025-01-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_printtemplate_delta_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_badge', to='home.userimage'),
        ),
        migrations.AddField(
            model_name='category',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_certificate', to='home.userimage'),
        ),
    ]
