# Generated by Django 5.1.1 on 2025-01-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
    ]
