# Generated by Django 5.1.1 on 2025-01-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_award_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_award', to='home.award'),
        ),
    ]
