# Generated by Django 5.1.1 on 2025-01-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_participant_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(help_text='До 100 символов', max_length=100, verbose_name='Фамилия'),
        ),
    ]
