# Generated by Django 5.1.1 on 2025-01-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_profile_sort_award_profile_sort_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_registration',
            field=models.BooleanField(default=True, verbose_name='Регистрация команды'),
        ),
    ]
