# Generated by Django 5.1.1 on 2025-02-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_printtemplate_print_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printtemplate',
            name='print_text',
            field=models.TextField(default=models.CharField(choices=[('event', 'Мероприятие'), ('category', 'Категория'), ('competency', 'Компетенция (номинация)'), ('fio', 'Фамилия Имя Отчество'), ('text', 'Текст участника'), ('custom_text', 'Произвольный техт')], max_length=25), verbose_name='Текст для печати'),
        ),
    ]
