# Generated by Django 5.1.1 on 2025-02-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_printtemplate_print_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printtemplate',
            name='print_text',
            field=models.TextField(verbose_name='Текст для печати'),
        ),
    ]
