# Generated by Django 5.1.1 on 2025-02-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_printtemplate_print_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printtemplate',
            name='delta_x',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='print_text',
        ),
    ]
