# Generated by Django 5.1.1 on 2025-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_printtemplate_delta_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='font_leading',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
