# Generated by Django 5.1.1 on 2025-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_printtemplate_font_leading'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='delta_x',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='delta_y',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='font_alignment',
            field=models.PositiveSmallIntegerField(choices=[('0', 'Лево'), ('1', 'По центр'), ('2', 'Право'), ('4', 'По ширине')], default=0),
        ),
    ]
