# Generated by Django 5.1.1 on 2025-04-06 06:29

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_profile_sort_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfont',
            name='font',
            field=models.FileField(null=True, upload_to=home.models.user_directory_path),
        ),
    ]
