# Generated by Django 5.1.1 on 2025-04-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_userfont_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='user_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_template_font', to='home.userfont'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='user_image_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user_image_related', to='home.userimage'),
        ),
    ]
