# Generated by Django 5.1.1 on 2025-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_printtemplate_after_print_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
