# Generated by Django 5.1.1 on 2025-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_participant_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема доклада'),
        ),
    ]
