# Generated by Django 5.1.1 on 2025-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_participant_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printtemplate',
            name='print_item',
            field=models.CharField(choices=[('event', 'Мероприятие'), ('category', 'Категория'), ('competency', 'Компетенция (номинация)'), ('fio', 'Фамилия Имя Отчество'), ('organization', 'Организация'), ('job_title', 'Должность'), ('text', 'Текст участника'), ('custom_text', 'Произвольный техт')], max_length=25),
        ),
    ]
