# Generated by Django 5.1.1 on 2025-04-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_printtemplate_print_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='competency',
        ),
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_competency', to='home.category'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
