# Generated by Django 5.1.1 on 2025-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sort_all_events_image',
            field=models.CharField(default='created_date', max_length=25),
        ),
    ]
