# Generated by Django 5.1.1 on 2025-05-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_profile_sort_all_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='printimage',
            name='print_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_image', to='home.alleventsimage'),
        ),
    ]
