# Generated by Django 5.1.1 on 2025-07-15 11:21

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_printimage_print_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='printimage',
            name='home_printimage',
            field=models.ImageField(null=True, upload_to=home.models.user_directory_path),
        ),
    ]
