# Generated by Django 5.1.1 on 2025-07-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_printimage_home_printimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printimage',
            name='home_printimage',
        ),
    ]
