# Generated by Django 5.1.1 on 2025-07-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_remove_printimage_image'),
        ('home', '0078_remove_printimage_home_printimage'),
    ]

    operations = [
    ]
