# Generated by Django 5.1.1 on 2025-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_merge_20250731_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printtemplate',
            name='after_print_text',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='before_print_text',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='print_item',
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='print_text',
            field=models.TextField(blank=True, null=True, verbose_name='Шаблон печати'),
        ),
    ]
