# Generated by Django 5.1.1 on 2025-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_remove_printtemplate_after_print_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sort_print_template',
            field=models.CharField(default='created_date', max_length=25),
        ),
    ]
