# Generated by Django 5.1.1 on 2025-11-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_profile_sort_print_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='print_title',
            field=models.TextField(default='text', verbose_name='Название для печати'),
            preserve_default=False,
        ),
    ]
